from fastapi import FastAPI,File,UploadFile,Header
from storage import upload_to_gcs
from embedding import get_image_embedding
from db import save_content
from db import db
from matcher import find_matches
from datetime import datetime
from email_service import send_email
import os
os.makedirs("temp", exist_ok=True)

import shutil
app = FastAPI()
def get_current_user(authorization: str = Header(default="test_user")):
    return authorization
@app.get("/")
def read_root():
    return {"message": "DigitalAssetProtection AI running"}
@app.post("/upload")
def upload_file(file:UploadFile=File(...),authorization: str = Header(default="test_user")):
    user_id = get_current_user(authorization)
    file_location = f"temp/{file.filename}"

    with open(file_location,"wb") as buffer:
        shutil.copyfileobj(file.file,buffer)
    
    url = upload_to_gcs(file_location, file.filename)
    dna_vector = get_image_embedding(file_location)
    #dna_vector = [0.1] * 128
    matches = find_matches(dna_vector)
    current_time = datetime.now()
    infringements = []

    for match in matches:
        if match["owner_id"] != user_id:
            infringements.append(match)
            alert = {
                "owner_id": match["owner_id"],
                "violator_id": user_id,
                "content_id": match["file_id"],
                "similarity": match["similarity"],
                "risk": get_risk(match["similarity"]),
                "timestamp": current_time
            }

            db.collection("alerts").add(alert)


    parent_id = None
    if matches:
        parent_id = matches[0]["file_id"]
    data = {
            "filename": file.filename,
            "url": url,
            "embedding": list(dna_vector),
            "owner_id": user_id,
            "derived_from": parent_id,
            "timestamp": current_time
            }
    save_content(data)
    return {"message": "Asset Protected",
            "url": url,
            "dna_length": len(dna_vector),
            "matches": matches,
            "infringements": infringements,
            "status": "Success"}
def get_risk(similarity):
    if similarity > 0.95:
        return "HIGH"
    elif similarity > 0.85:
        return "MEDIUM"
    return "LOW"

@app.get("/graph")
def get_graph():
    contents = db.collection("contents").stream()

    nodes = []
    edges = []

    for doc in contents:
        data = doc.to_dict()
        node_id = doc.id

        nodes.append({
            "id": node_id,
            "label": data.get("filename")
        })

        if data.get("derived_from"):
            edges.append({
                "from": data["derived_from"],
                "to": node_id
            })

    return {
        "nodes": nodes,
        "edges": edges
    }

@app.post("/generate-takedown")
def generate_takedown(alert_id: str):

    alert_doc = db.collection("alerts").document(alert_id).get()

    if not alert_doc.exists:
        return {"error": "Alert not found"}

    alert = alert_doc.to_dict()

    return {
        "notice": f"""
Subject: Unauthorized Use of Digital Asset

This is to notify that your content has been identified as unauthorized usage.

Original Owner: {alert['owner_id']}
Uploader: {alert['violator_id']}
Similarity Score: {alert['similarity']}
Risk Level: {alert['risk']}

Please remove this content immediately.

Generated by DigitalAssetProtection AI
"""
    }

@app.post("/send-takedown")
def send_takedown_email(to_email,alert_id):
    alert_doc = db.collection("alerts").document(alert_id).get()
    if not alert_doc.exits:
        return {"error":"Alert Not Found"}
    alert = alert.to_dict()
    notice = f"""
Subject: Unauthorized Use of Digital Asset

This content has been identified as unauthorized usage.

Original Owner: {alert['owner_id']}
Uploader: {alert['violator_id']}
Similarity Score: {alert['similarity']}
Risk Level: {alert['risk']}

Please remove this content immediately.

Generated by DigitalAssetProtection AI
"""
    success = send_email(to_email,"Takedown Notice: Digital Asset Infringement",notice)
    if success:
        return {"message":"Email sent successfully"}
    else:
        return {"error":"Email Failed"}